[[plugins]]
  package = "@netlify/plugin-inline-cache"

[build]
  command = "npm run build"
  publish = "build/"

[[headers]]
  for = "/\\.svg$/"
  [headers.values]
    Content-Type = "image/svg+xml"
